package com.example.BankingApplication.Domain;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Entity
@Getter
@Setter
public class Account {

    @Id
    private String accountNumber;

    private String customerID;
    private String panID;

    // Many-to-one relationship with PersonalDetails (Each Account is linked to one PersonalDetails)
    @ManyToOne
    @JoinColumn(name = "personal_details_account_number", referencedColumnName = "accountNumber")
    private PersonalDetails personalDetails;

    // Constructor, Getters, and Setters generated by Lombok
}
