package com.example.BankingApplication.Domain;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Entity
@Getter
@Setter
public class PersonalDetails {

    @Id
    private String accountNumber;  // Used as the primary key (for the relationship)

    private String name;
    private String address;

    // One-to-one relationship with Account (Each PersonalDetails is linked to one Account)
    @OneToOne(mappedBy = "personalDetails")
    private Account account;

    // Constructor, Getters, and Setters generated by Lombok
}
